version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.2.0
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

#docker-compose -f docker-compose.yml up -d
#https://developer.confluent.io/quickstart/kafka-docker/

#command to publish message to the topic
#docker exec --interactive --tty broker kafka-console-producer --bootstrap-server broker:9092 --topic upperCase-in-0

#command to subscribe message to the topic
#docker exec --interactive --tty broker kafka-console-consumer --bootstrap-server broker:9092 --topic upperCase-out-0


#youtube link
#https://www.youtube.com/watch?v=5Mgni6AYnWg&list=RDCMUC7yfnfvEUlXUIfm8rGLwZdA&start_radio=1&rv=5Mgni6AYnWg&t=23
#github link to the youtube link guy
#https://github.com/schacko-samples/s1p-2019-scst-kafka-talk